name: CI devops 2021 EPF
on:
  push:
    branches: [main, develop]
  pull_request:
jobs:
  build-and-test-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      #- name: Login to sonar
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      #  run: mvn -B verify sonar:sonar -Dsonar.projectKey=TP-02-DevOps -Dsonar.organization=bruugs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml
 

 
  build-and-push-docker-image:
    needs: build-and-test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3
        
      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}
        
      - name: build image and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/TP-02-DevOps:simple-api
          push: ${{ github.ref == 'refs/heads/master' }}
          
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/TP-02-DevOps:database
          push: ${{ github.ref == 'refs/heads/master' }}
          
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          context: ./httpd
          tags: ${{secrets.DOCKERHUB_USERNAME}}/TP-02-DevOps:httpd
          push: ${{ github.ref == 'refs/heads/master' }}
